FROM php:8.0-apache

RUN apt-get update && apt-get install -y \
                libfreetype6-dev \
                libpng-dev \
                libmcrypt-dev \
                default-mysql-client \
                vim \
                nano \
                git \
                libc-client-dev \
                libxml2-dev \
                sudo \
                wget \
                ssmtp \
                libzip-dev \
                && docker-php-ext-install gd iconv pdo pdo_mysql mysqli zip

RUN pecl install xdebug

RUN echo "alias ll='ls $LS_OPTIONS -l'" >> /root/.bashrc

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./files/php/*.ini /usr/local/etc/php/conf.d/

ARG DOCKER_HOST_PLATFORM

COPY ./files/php/platform/*-${DOCKER_HOST_PLATFORM}.ini /usr/local/etc/php/conf.d/

COPY ./files/ssmtp/ssmtp.conf /etc/ssmtp/

RUN echo "zend_extension=$(find /usr/local/lib/php/extensions -name 'xdebug.so')" \
        >> /usr/local/etc/php/conf.d/ext-xdebug.ini

COPY ./files/apache/*.conf /etc/apache2/conf-available/

RUN a2enmod rewrite

# RUN a2enmod <another_module>

COPY ./files/docker-web-init.sh /usr/local/bin/

CMD docker-web-init.sh && apache2-foreground
